p = input('Digite algo: ')
print(f'O tipo primitivo desse valor é {type(p)}')
print(f'Só tem espaços ?  {p.isspace()}')
print(f'É um número ?  {p.isnumeric()}')
print(f'É alfabético ?  {p.isalpha()}')
print(f'É alfanumérico ? {p.isalnum()}')
print(f'Está em maiúscula ? {p.isupper()}')
print(f'Está em minúuscula ?  {p.islower()}')
print(f'Está capitalizada ? {p.isdigit()}')
